menu:
#- {name: 'people', url: '/people'}
#- {name: 'publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
#- {name: 'cv', url: '/cv'}
#- {name: 'contact', url: '/contact'}

projects:
- {name: 'Unseen Object Detection', 
   company_and_date: 'ARBEON (알비언), 2022.12 - present', 
   description: "Multi-model (image-text pair)을 활용하여 한번도 보지 못한 세상의 모든 객체를 검출하는 object detection model 개발. 
    온디바이스 (andorid, ios) 포팅 및 데모 앱 개발. 안드로이드 유저를 위한 초 경량화 object detection model 개발: galax s22 기준 R@1 정확도 95% 이상, inference time 12mes 달성.
    아이폰 플래그쉽 유저를 위한 고도화된 object detection model 개발 Segment Anything Model 의 points embedding 에서 영감을 얻어",
   department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}


courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
